# Generated by Django 3.0.3 on 2020-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sermon_by', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
    ]
